version: '3.3'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: java_practice
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - storage2:/var/lib/mysql

  app:
    build: ./
    working_dir: /app
    depends_on:
      - database
    ports:
      - "8090:8080"
    volumes:
      - ".:/app"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: java_practice
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app/target/MVC-1.0.jar

volumes:
    storage2:
